### ISSUE TITLE
Folder mapping not correct: files in /lnd/.lnd expected in /root/.lnd by lncli

### ISSUE THREAD

**Issue by teunehv** [LN-Zap/docker-lnd#5]
I started the container using the command below (as described in https://github.com/LN-Zap/docker-lnd)

`docker run -v lnd-data:/lnd --name=lnd-node -d \
    -p 9735:9735 \
    -p 10009:10009 \
    lnzap/lnd:latest \
    --bitcoin.active \
    --bitcoin.testnet \
    --debuglevel=info \
    --bitcoin.node=neutrino \
    --neutrino.connect=testnet1-btcd.zaphq.io \
    --neutrino.connect=testnet2-btcd.zaphq.io \
    --autopilot.active \
    --rpclisten=0.0.0.0:10009`

The container is starting
Certificates are generated

Certifactes present in /lnd/.lnd/

**Expected:**
- I can perform lncli commands, i.e. getinfo or create

**Actual:**
- commands give the error: [lncli] open /root/.lnd/tls.cert: no such file or directory

**Comment by mrfelton** [comment]
The container runs as `lnd` user, not `root`. Pass `-u lnd` to your `docker run` command.

**Comment by teunehv** [comment]
Great, thanks. That worked.
